name: Fetch Road State

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 执行
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  fetch-road-state:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3  # 更新为 v3 版本

      - name: Fetch Road State Data
        run: |
          set -e  # 遇到错误时停止执行
          ${{ secrets.API_SCRIPT }}  # 执行爬取脚本
          if [ ! -s road_state.json ]; then  # 检查文件是否存在且非空
            echo "road_state.json is empty or missing. Exiting..."
            exit 1  # 如果文件为空或不存在，则退出并标记为失败
          fi
        shell: bash

      - name: Commit and push changes
        if: success()  # 只有当爬取成功时才继续
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add road_state.json
          git commit -m "Update road state data - $(date +'%Y-%m-%d')"
          git push --force
